server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    location /api/ { proxy_pass http://backend:8000; proxy_buffering off; proxy_cache off; add_header X-Accel-Buffering no; }
    location /electric/ { proxy_pass http://electric:3000/; proxy_buffering off; proxy_cache off; add_header X-Accel-Buffering no; }
    location / { try_files $uri $uri/ /index.html; }
}
